---
- hosts: all
  sudo: yes
  tasks:
    - apt: name=build-essential
    - apt: name=python-meld3
    - apt: name=ruby
    - apt: name=git
    - apt: name=libssl-dev
    - apt: name=libcurl3
    - apt: name=libcurl4-openssl-dev
    - apt: name=bison
    - apt: name=libbison-dev
    - apt: name=libjpeg-turbo8
    - apt: name=libjpeg-turbo8-dev
    - apt: name=libpng12-0
    - apt: name=libpng12-dev
    - apt: name=libmcrypt4
    - apt: name=libmcrypt-dev
    - apt: name=readline-common
    - apt: name=libreadline-dev
    - apt: name=libtidy-0.99-0
    - apt: name=libtidy-dev
    - apt: name=libxml2-dev
    - apt: name=libxslt1-dev
    - apt: name=mysql-server
